all:	fig1 fig2 fig3 fig3_poor1 fig3_poor2 pc_v1 fig6_broken fig8_broken2 fig10_finally fig1112_final fig13_covering

fig1:	fig1.o
			gcc -o fig1 fig1.o

fig1.o:	fig1.c
				gcc -Wall -c fig1.c

fig2:	fig2.o
			gcc -o fig2 fig2.o

fig2.o:	fig2.c
				gcc -Wall -c fig2.c

fig3:	fig3.o
			gcc -o fig3 fig3.o

fig3.o:	fig3.c
				gcc -Wall -c fig3.c

fig3_poor1:	fig3_poor1.o
			gcc -o fig3_poor1 fig3_poor1.o

fig3_poor1.o:	fig3_poor1.c
				gcc -Wall -c fig3_poor1.c

fig3_poor2:	fig3_poor2.o
			gcc -o fig3_poor2 fig3_poor2.o

fig3_poor2.o:	fig3_poor2.c
				gcc -Wall -c fig3_poor2.c

pc_v1:	pc_v1.o
			gcc -o pc_v1 pc_v1.o

pc_v1.o:	pc_v1.c
				gcc -Wall -c pc_v1.c

fig6_broken:	fig6_broken.o
			gcc -o fig6_broken fig6_broken.o

fig6_broken.o:	fig6_broken.c
				gcc -Wall -c fig6_broken.c

fig8_broken2:	fig8_broken2.o
			gcc -o fig8_broken2 fig8_broken2.o

fig8_broken2.o:	fig8_broken2.c
				gcc -Wall -c fig8_broken2.c

fig10_finally:	fig10_finally.o
			gcc -o fig10_finally fig10_finally.o

fig10_finally.o:	fig10_finally.c
				gcc -Wall -c fig10_finally.c

fig1112_final:	fig1112_final.o
			gcc -o fig1112_final fig1112_final.o

fig1112_final.o:	fig1112_final.c
				gcc -Wall -c fig1112_final.c

fig13_covering:	fig13_covering.o
			gcc -o fig13_covering fig13_covering.o

fig13_covering.o:	fig13_covering.c
				gcc -Wall -c fig13_covering.c

clean:
					rm -f *.o fig1 fig2 fig3 fig3_poor1 fig3_poor2 pc_v1 fig6_broken fig8_broken2 fig10_finally fig1112_final fig13_covering
